---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
  #
  # - name: Create /etc/modprobe.d/CIS.conf with root ownership & mode
  #   file: path=/etc/modprobe.d/CIS.conf state=touch owner=root group=root mode=0600
  #   changed_when: false
  #   tags:
  #     - notscored
  #     - section1.1
  #     - section1.1.18
  #     - section1.1.19
  #     - section1.1.20
  #     - section1.1.21
  #     - section1.1.22
  #     - section1.1.23
  #     - section1.1.24
  #
  # - name: 1.1.18 Disable Mounting of cramfs Filesystems (Not Scored)
  #   lineinfile: >
  #     state=present
  #     dest=/etc/modprobe.d/CIS.conf
  #     line="install cramfs /bin/true"
  #   tags:
  #     - notscored
  #     - section1.1
  #     - section1.1.18
  #
  # - name: 1.1.19 Disable Mounting of freevxfs Filesystems (Not Scored)
  #   lineinfile: >
  #     state=present
  #     dest=/etc/modprobe.d/CIS.conf
  #     line="install freevxfs /bin/true"
  #   tags:
  #     - notscored
  #     - section1.1
  #     - section1.1.19
  #
  # - name: 1.1.20 Disable Mounting of jffs2 Filesystems (Not Scored)
  #   lineinfile: >
  #     state=present
  #     dest=/etc/modprobe.d/CIS.conf
  #     line="install jffs2 /bin/true"
  #   tags:
  #     - notscored
  #     - section1.1
  #     - section1.1.20
  #
  # - name: 1.1.21 Disable Mounting of hfs Filesystems (Not Scored)
  #   lineinfile: >
  #     state=present
  #     dest=/etc/modprobe.d/CIS.conf
  #     line="install hfs /bin/true"
  #   tags:
  #     - notscored
  #     - section1.1
  #     - section1.1.21
  #
  # - name: 1.1.22 Disable Mounting of hfsplus Filesystems (Not Scored)
  #   lineinfile: >
  #     state=present
  #     dest=/etc/modprobe.d/CIS.conf
  #     line="install hfsplus /bin/true"
  #   tags:
  #     - notscored
  #     - section1.1
  #     - section1.1.22
  #
  # - name: 1.1.23 Disable Mounting of squashfs Filesystems (Not Scored)
  #   lineinfile: >
  #     state=present
  #     dest=/etc/modprobe.d/CIS.conf
  #     line="install squashfs /bin/true"
  #   tags:
  #     - notscored
  #     - section1.1
  #     - section1.1.23
  #
  # - name: 1.1.24 Disable Mounting of udf Filesystems (Not Scored)
  #   lineinfile: >
  #     state=present
  #     dest=/etc/modprobe.d/CIS.conf
  #     line="install udf /bin/true"
  #   tags:
  #     - notscored
  #     - section1.1
  #     - section1.1.24
  #
  # - name: 1.2.4 Check to see if rhnsd daemon is installed (Not Scored)
  #   stat: path=/etc/init.d/rhnsd
  #   register: rhnsd_service
  #   when: ansible_distribution == "RedHat"
  #   tags:
  #     - notscored
  #     - section1.2
  #     - section1.2.4
  #
  # - name: 1.2.4 Disable the rhnsd Daemon (Not Scored)
  #   action: command /sbin/chkconfig rhnsd off
  #   when: ansible_distribution == "RedHat"
  #   tags:
  #     - notscored
  #     - section1.2
  #     - section1.2.4

  # - name: 1.3.1 Install AIDE (Scored)
  #   yum: >
  #     name=aide
  #     state=present
  #   when: configure_aide
  #   tags:
  #     - scored
  #     - section1.3
  #     - section1.3.1
  #
  # - name: 1.3.1 Ensure AIDE is installed (Scored)
  #   command: >
  #     /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  #     creates=/var/lib/aide/aide.db.gz
  #   when: configure_aide
  #   tags:
  #     - scored
  #     - section1.3
  #     - section1.3.1
  #
  # - name: 1.3.1 Install AIDE (check is prelink installed) (Scored)
  #   stat: path=/usr/sbin/prelink
  #   register: prelink_stat
  #   when: configure_aide
  #   tags:
  #     - scored
  #     - section1.3
  #     - section1.3.1
  #
  # - name: 1.3.1 Install AIDE (Disable Prelinking) (Scored)
  #   lineinfile: >
  #     state=present
  #     dest=/etc/sysconfig/prelink
  #     regexp=^PRELINKING=
  #     line=PRELINKING=no
  #     create=yes
  #   when:
  #     - configure_aide
  #     - prelink_stat.stat.exists
  #   tags:
  #     - scored
  #     - section1.3
  #     - section1.3.1
  #
  # - name: 1.3.2 Ensure filesystem integrity is regularly checked (Scored)
  #   cron: >
  #     name="Run AIDE (CIS 1.3.2)"
  #     minute="0"
  #     hour="5"
  #     job="/usr/sbin/aide --check"
  #   when: configure_aide
  #   tags:
  #     - scored
  #     - section1.3
  #     - section1.3.2

# 1.4 Secure Boot Settings
  - name: 1.4.1 Ensure permissions on bootloader config are configured (Scored)
    shell: |
      chown root:root /boot/grub/grub.conf
      chmod og-rwx /boot/grub/grub.conf
    when: ansible_distribution == "CentOS"
    when: ansible_distribution == "Final"
    when: ansible_distribution == "6.5"
    tags:
       - notscored
       - section1.4
       - section1.4.1


  - name: 1.4.2 Ensure bootloader password is set (Scored)
    debug: msg="add later."
    tags:
       - notscored
       - section1.4
       - section1.4.2

  - name: 1.4.3 Ensure authentication required for single user mode (Scored)
    debug: msg="add later."
    tags:
      - notscored
      - section1.4
      - section1.4.3

  - name: 1.4.4 Ensure interactive boot is not enabled (Not Scored)
    debug: msg="add later."
    tags:
      - notscored
      - section1.4
      - section1.4.4
# 1.5 Additional Process Hardening
  - name: 1.5.1 Ensure core dumps are restricted (Scored)
    lineinfile:
        dest: /etc/security/limits.conf
        state: present
        line: "* hard core 0"
    tags:
     - scored
     - section1.5
     - section1.5.1

  - name: 1.5.1 Ensure core dumps are restricted (Scored)
    lineinfile:
        dest: /etc/sysctl.conf
        state: present
        line: fs.suid_dumpable = 0
    tags:
      - scored
      - section1.5
      - section1.5.1

  - name: 1.5.2 Ensure XD/NX support is enabled (Scored)
    debug: msg="add later."
    tags:
      - scored
      - section1.5
      - section1.5.2

  - name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled (Scored)
    lineinfile:
        dest: /etc/sysctl.conf
        state: present
        line: kernel.randomize_va_space = 2
    tags:
      - scored
      - section1.5
      - section1.5.3

  - name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled (Scored)
    shell: |
        sysctl -w kernel.randomize_va_space=2
    tags:
      - scored
      - section1.5
      - section1.5.3

  - name: 1.5.4 Ensure prelink is disabled (Scored)
    shell: |
          yum remove prelink
    ignore_errors: yes
    when: perlink_remove
    tags:
     - scored
     - section1.5
     - section1.5.4

# 1.6 Mandatory Access Control

  - name: 1.6.1 Ensure Mandatory Access Control Software is Installed
    debug: msg="1.6.1 Ensure Mandatory Access Control Software is Installed."
    tags:
      - scored
      - section1.6
      - section1.6.1

  - name: 1.6.1.1 Ensure SELinux or AppArmor are installed (Scored)
    shell: |
       yum install libselinux
    ignore_errors: yes
    when: install_selinux
    tags:
      - scored
      - section1.6.1.1
      - section1.6

# 1.6.2 Configure SELinux

  - name: 1.6.2.1 Ensure SELinux is not disabled in bootloader configuration (Scored)
    debug: msg="add later."
    tags:
      - scored
      - section1.6
      - section1.6.2
      - section1.6.2.1

  - name: 1.6.2.2 Ensure the SELinux state is enforcing (Scored)
    selinux:
      policy: targeted
      state: enforcing
    when: enable_selinux
    tags:
      - scored
      - section1.6
      - section1.6.2
      - section1.6.2.2

  - name: 1.6.2.4 Ensure SETroubleshoot is not installed (Scored)
    shell: |
      yum remove setroubleshoot
    when: setroubleshoot
    ignore_errors: yes
    tags:
      - scored
      - section1.6
      - section1.6.2
      - section1.6.2.4

  - name: 1.6.2.5 Ensure the MCS Translation Service (mcstrans) is not installed
    shell: |
      yum remove mcstrans
    when: remove_mcstrans
    ignore_errors: yes
    tags:
     - scored
     - section1.6
     - section1.6.2
     - section1.6.2.5

  - name: 1.6.2.6 Ensure no unconfined daemons exist (Scored)
    debug: msg="add later."
    tags:
      - scored
      - section1.6
      - section1.6.2.6


# 1.6.3 Configure AppArmor

#1.7 Warning Banners
#1.7.1 Command Line Warning Banners
  - name: 1.7.1.2 Ensure local login warning banner is configured properly
    shell: |
       echo "Authorized uses only. All activity may be monitored and reported." > /etc/issue
    tags:
      - scored
      - section1.7
      - section1.7.1.2

  - name: 1.7.1.3 Ensure local login warning banner is configured properly
    shell: |
       echo "Authorized uses only. All activity may be monitored and reported." > /etc/issue.net
    tags:
      - scored
      - section1.7
      - section1.7.1.3

  - name: 1.7.1.4 Ensure permissions on /etc/motd are configured (Scored)
    shell: |
       chown root:root /etc/motd
       chmod 644 /etc/motd
    tags:
      - scored
      - section1.7
      - section1.7.1.4

  - name: 1.7.1.5 Ensure permissions on /etc/motd are configured (Scored)
    shell: |
       chown root:root /etc/issue
       chmod 644 /etc/issue
    tags:
      - scored
      - section1.7
      - section1.7.1.5

  - name: 1.7.1.6 Ensure permissions on /etc/issue.net are configured (Scored)
    shell: |
       chown root:root /etc/issue.net
       chmod 644 /etc/issue.net
    tags:
      - scored
      - section1.7
      - section1.7.1.5

  - name: 1.7.2 Ensure GDM login banner is configured (Scored)
    copy:
      dest: "/etc/gdm3/greeter.dconf-defaults"
      content: |
            [org/gnome/login-screen]
            banner-message-enable=true
            banner-message-text='Authorized uses only. All activity may be monitored and
            reported.'
    when: gdm_login_banner
    ignore_errors: yes
    tags:
       - scored
       - section1.7.2

#1.8 Ensure updates, patches, and additional security software are installed (Not Scored)

  - name: 1.8 Ensure updates, patches, and additional security software are installed (Not Scored)
    shell: |
       yum update
    when: yum_update
    tags:
      - scored
      - section1.8
